name: MitchPrisonsCore
version: '${project.version}'
main: mitch.prisonscore.MitchPrisonsCore
api-version: '1.19'
author: ReklessMitch
description: MitchPrisonsCore
depend:
  - MassiveCore
  - WorldBorderAPI
  - ProtocolLib
  - LuckPerms
  - ModelEngine


