name: MitchPrisonsCore
version: '${project.version}'
main: me.reklessmitch.mitchprisonscore.MitchPrisonsCore
api-version: '1.19'
author: ReklessMitch
description: MitchPrisonsCore
depend:
  - MassiveCore
  - WorldBorderAPI
  - ProtocolLib


